// 文件路径：tailwind.config.js

export default {
  darkMode: ["class", "[data-theme=\"dark\"]"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: "var(--brand)",
          50: "var(--brand-50)",
          100: "var(--brand-100)",
          200: "var(--brand-200)",
          300: "var(--brand-300)",
          400: "var(--brand-400)",
          500: "var(--brand-500)",
          600: "var(--brand-600)",
          700: "var(--brand-700)",
          800: "var(--brand-800)",
          900: "var(--brand-900)",
        },
        neutral: {
          50: "var(--neutral-50)",
          100: "var(--neutral-100)",
          200: "var(--neutral-200)",
          300: "var(--neutral-300)",
          400: "var(--neutral-400)",
          500: "var(--neutral-500)",
          600: "var(--neutral-600)",
          700: "var(--neutral-700)",
          800: "var(--neutral-800)",
          900: "var(--neutral-900)",
          950: "var(--neutral-950)",
        },
        success: "var(--success)",
        warning: "var(--warning)",
        error: "var(--error)",
        info: "var(--info)",
      },
      backgroundColor: {
        "background-base": "var(--bg-base)",
        "background-elevated": "var(--bg-elevated)",
        "background-secondary": "var(--bg-secondary)",
        "background-tertiary": "var(--bg-tertiary)",
        "background-muted": "var(--bg-muted)",
        "background-light-base": "var(--bg-light-base)",
        "background-light-elevated": "var(--bg-light-elevated)",
        "background-light-secondary": "var(--bg-light-secondary)",
      },
      textColor: {
        "text-primary": "var(--text-1)",
        "text-secondary": "var(--text-2)",
        "text-tertiary": "var(--text-3)",
        "text-muted": "var(--text-muted)",
        "text-inverse": "var(--text-inverse)",
      },
      borderColor: {
        "border-primary": "var(--border-primary)",
        "border-secondary": "var(--border-secondary)",
        "border-muted": "var(--border-muted)",
      },
      ringColor: {
        brand: "var(--brand)",
        success: "var(--success)",
        warning: "var(--warning)",
        error: "var(--error)",
      },
      ringOffsetColor: {
        background: "var(--bg-base)",
        "background-base": "var(--bg-base)",
        "background-elevated": "var(--bg-elevated)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        inset: "var(--shadow-inset)",
      },
      borderRadius: {
        DEFAULT: "var(--radius)",
        sm: "var(--radius-sm)",
        md: "var(--radius)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      fontFamily: {
        sans: ["var(--font-family)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      height: {
        control: "var(--control-h)",
        "control-sm": "var(--control-h-sm)",
        "control-lg": "var(--control-h-lg)",
      },
      width: {
        control: "var(--control-h)",
      },
      transitionTimingFunction: {
        brand: "var(--ease-brand)",
        in: "var(--ease-in)",
        out: "var(--ease-out)",
        "in-out": "var(--ease-in-out)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
      },
      zIndex: {
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        fixed: "var(--z-fixed)",
        "modal-backdrop": "var(--z-modal-backdrop)",
        modal: "var(--z-modal)",
        popover: "var(--z-popover)",
        tooltip: "var(--z-tooltip)",
        toast: "var(--z-toast)",
      },
    },
  },
  plugins: [],
}
