pub mod smart_selection;
pub mod universal_ui;
pub mod adb;
pub mod employees;
pub mod contacts;
pub mod image_optimization;
pub mod system_diagnostic;
pub mod file_manager;
pub mod xml_cache;
pub mod intelligent_analysis;
pub mod execution_v3;
pub mod version_control;
pub mod automation;
pub mod enhanced_location;
pub mod lead_hunt;
pub mod script_manager;
pub mod prospecting;
pub mod ai;
pub mod ui_dump;  // ✅ UI Dump 多模式系统
