# .github/workflows/release-tauri.yml
name: 跨平台打包与发布（Tauri）

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  build-windows:
    name: Windows 安装包
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - name: 安装依赖
        run: npm ci
      - name: 构建 Tauri（生成 .msi/.exe）
        run: npm run tauri build
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}   # 可选：代码签名
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
      - uses: softprops/action-gh-release@v2
        with:
          files: src-tauri/target/release/bundle/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: macOS 安装包
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - name: 安装依赖
        run: npm ci
      - name: 构建 Tauri（生成 .dmg/.app）
        run: npm run tauri build
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}         # 可选：签名
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERT_PWD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_IDENTITY }}
      - uses: softprops/action-gh-release@v2
        with:
          files: src-tauri/target/release/bundle/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    name: Linux 安装包
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - name: 安装依赖
        run: npm ci
      - name: 构建 Tauri（生成 .AppImage/.deb）
        run: npm run tauri build
      - uses: softprops/action-gh-release@v2
        with:
          files: src-tauri/target/release/bundle/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}